apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobros-landing-preferencias
  namespace: iris
  labels:
    cattle.io/creator: celulaBillingAndPayment
    app: cobros-landing-preferencias
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: cobros-landing-preferencias
  template:
    metadata:
      labels:
        app: cobros-landing-preferencias
    spec:
      containers:
        - name: cobros-landing-preferencias
          image: imagekeyword
          resources:
            limits:
              cpu: "1" 
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: Always
          securityContext:
            capabilities: {}
            privileged: false
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          stdin: true
          tty: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
      dnsConfig: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
apiVersion: v1
kind: Service
metadata:
  name: cobros-landing-preferencias
  namespace: iris
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: cobros-landing-preferencias
  sessionAffinity: None
  type: ClusterIP